### ISSUE TITLE
Is such service worth the cost?

### ISSUE THREAD

**Issue by yschua** [skeleton0/nordvpn-update#1]
Do you have this on 24/7?

**Comment by skeleton0** [comment]
I pretty much only use it when I need it. Although when my NordVPN subscription lapses I'll probably subscribe to another VPN out of principle due to their use of dark patterns on their website. I think most of the VPN companies do similar things though for some reason.

**Comment by yschua** [comment]
I've always wondered why VPN provider run ads so rampantly, especially on YouTube. They must have so much customers and boatloads of cash and are seemingly turning this service into a necessity.

**Comment by skeleton0** [comment]
To answer the original question, yeah I think the service is worth the cost depending on if you need it. Especially given the fact that it's quite inexpensive.
